import UIKit

protocol TutoStep1ViewControllerNavigation: class {
  // Add here functions to navigate away from this screen, to ask the Coordinator to show another screen
  func showTutorialStep2()
}

final class TutoStep1ViewController: UIViewController {

  weak var coordinator: TutoStep1ViewControllerNavigation?
  
  // MARK: - Private Properties
  
  // MARK: - Setup
  
  static func instantiate(/* dependencies: Dependencies */) -> TutoStep1ViewController {
    let vc = StoryboardScene.Tutorial.tutoStep1ViewController.instantiate() // Constants generated by SwiftGen
    // vc.dependences = dependencies
    return vc
  }
  
  // MARK: - Internal Funcs

  @IBAction func goNext() {
    self.coordinator?.showTutorialStep2()
  }
}
